package com.emergencypreparedness.manager.entities;

import androidx.room.Entity;
import androidx.room.Ignore;
import androidx.room.PrimaryKey;

/**
 * Room entity representing an emergency preparedness kit.
 * <p>
 * A kit can contain multiple kit items. Supports optional notifications with configurable frequency
 * ("MONTHLY", "QUARTERLY", "YEARLY"). Notification time is managed globally via SharedPreferences.
 */
@Entity(tableName = "Kits")
public class Kit {

  //region Fields
  @PrimaryKey(autoGenerate = true)
  private int kitID;

  private String kitName;
  private String location;
  private String notes;

  private boolean notificationsEnabled;
  private String notificationFrequency; // "MONTHLY", "QUARTERLY", "YEARLY"
  //endregion

  //region Constructors

  /**
   * Creates a new kit. The kitID is auto-generated by Room.
   *
   * @param kitName               name of the kit
   * @param location              storage location (optional)
   * @param notes                 additional notes (optional)
   * @param notificationsEnabled  whether kit-level reminders are enabled
   * @param notificationFrequency frequency for reminders ("MONTHLY", "QUARTERLY", "YEARLY")
   */
  public Kit(
      String kitName,
      String location,
      String notes,
      boolean notificationsEnabled,
      String notificationFrequency
  ) {
    this.kitName = kitName;
    this.location = location;
    this.notes = notes;
    this.notificationsEnabled = notificationsEnabled;
    this.notificationFrequency = notificationFrequency;
  }

  /**
   * Creates an existing kit with a known ID (used for updates, queries, or deletions).
   *
   * @param kitID                 existing kit ID from database
   * @param kitName               name of the kit
   * @param location              storage location
   * @param notes                 additional notes
   * @param notificationsEnabled  whether kit-level reminders are enabled
   * @param notificationFrequency frequency for reminders
   */
  @Ignore
  public Kit(
      int kitID,
      String kitName,
      String location,
      String notes,
      boolean notificationsEnabled,
      String notificationFrequency
  ) {
    this.kitID = kitID;
    this.kitName = kitName;
    this.location = location;
    this.notes = notes;
    this.notificationsEnabled = notificationsEnabled;
    this.notificationFrequency = notificationFrequency;
  }

  /**
   * Default no-arg constructor (required for dummy objects in delete operations).
   */
  @Ignore
  public Kit() {
  }
  //endregion

  //region Getters and Setters
  public int getKitID() {
    return kitID;
  }

  public void setKitID(int kitID) {
    this.kitID = kitID;
  }

  public String getKitName() {
    return kitName;
  }

  public void setKitName(String kitName) {
    this.kitName = kitName;
  }

  public String getLocation() {
    return location;
  }

  public void setLocation(String location) {
    this.location = location;
  }

  public String getNotes() {
    return notes;
  }

  public void setNotes(String notes) {
    this.notes = notes;
  }

  public boolean isNotificationsEnabled() {
    return notificationsEnabled;
  }

  public void setNotificationsEnabled(boolean notificationsEnabled) {
    this.notificationsEnabled = notificationsEnabled;
  }

  public String getNotificationFrequency() {
    return notificationFrequency;
  }

  public void setNotificationFrequency(String notificationFrequency) {
    this.notificationFrequency = notificationFrequency;
  }
}
