package com.emergencypreparedness.manager.entities;

import androidx.room.Entity;
import androidx.room.Ignore;
import androidx.room.PrimaryKey;

/**
 * Room entity representing an item stored within a kit.
 * <p>
 * Each item belongs to one kit. Supports expiration and low-quantity notifications. Expiration
 * reminders: enabled + days before. Quantity reminders: notify on zero. Notification time is global
 * (via SharedPreferences).
 */
@Entity(tableName = "KitItems")

public class KitItem {

  //region Fields
  @PrimaryKey(autoGenerate = true)
  private int itemID;

  private int kitID;
  private String itemName;
  private int quantity;
  private int categoryID;
  private String expirationDate; // "MM/dd/yyyy" (optional)
  private String notes;

  private boolean expirationRemindersEnabled;
  private int notifyDaysBefore; // 0 = day-of, 3 = 3 days before, etc.
  private boolean notifyOnZero; // true = notify when quantity becomes 0
  //endregion

  //region Constructors

  /**
   * Creates a new kit item. The itemID is auto-generated by Room.
   *
   * @param kitID                      parent kit ID
   * @param itemName                   name of the item
   * @param quantity                   initial quantity
   * @param categoryID                 category ID
   * @param expirationDate             expiration date ("MM/dd/yyyy", optional)
   * @param notes                      optional notes
   * @param expirationRemindersEnabled whether expiration reminders are active
   * @param notifyDaysBefore           days before expiration to notify (0 = day-of)
   * @param notifyOnZero               whether to notify when quantity reaches zero
   */
  public KitItem(
      int kitID,
      String itemName,
      int quantity,
      int categoryID,
      String expirationDate,
      String notes,
      boolean expirationRemindersEnabled,
      int notifyDaysBefore,
      boolean notifyOnZero
  ) {
    this.kitID = kitID;
    this.itemName = itemName;
    this.quantity = quantity;
    this.categoryID = categoryID;
    this.expirationDate = expirationDate;
    this.notes = notes;
    this.expirationRemindersEnabled = expirationRemindersEnabled;
    this.notifyDaysBefore = notifyDaysBefore;
    this.notifyOnZero = notifyOnZero;

  }

  /**
   * Creates an existing kit item with a known ID (used for updates, queries, or deletions).
   *
   * @param itemID                     existing item ID from database
   * @param kitID                      parent kit ID
   * @param itemName                   name of the item
   * @param quantity                   current quantity
   * @param categoryID                 category ID
   * @param expirationDate             expiration date ("MM/dd/yyyy", optional)
   * @param notes                      optional notes
   * @param expirationRemindersEnabled whether expiration reminders are active
   * @param notifyDaysBefore           days before expiration to notify
   * @param notifyOnZero               whether to notify when quantity reaches zero
   */
  @Ignore
  public KitItem(
      int itemID,
      int kitID,
      String itemName,
      int quantity,
      int categoryID,
      String expirationDate,
      String notes,
      boolean expirationRemindersEnabled,
      int notifyDaysBefore,
      boolean notifyOnZero
  ) {
    this.itemID = itemID;
    this.kitID = kitID;
    this.itemName = itemName;
    this.quantity = quantity;
    this.categoryID = categoryID;
    this.expirationDate = expirationDate;
    this.notes = notes;
    this.expirationRemindersEnabled = expirationRemindersEnabled;
    this.notifyDaysBefore = notifyDaysBefore;
    this.notifyOnZero = notifyOnZero;
  }

  /**
   * Default no-arg constructor (required for dummy objects in delete operations).
   */
  @Ignore
  public KitItem() {
  }
  //endregion

  //region Getters and Setters
  public int getItemID() {
    return itemID;
  }

  public void setItemID(int itemID) {
    this.itemID = itemID;
  }

  public int getKitID() {
    return kitID;
  }

  public void setKitID(int kitID) {
    this.kitID = kitID;
  }

  public String getItemName() {
    return itemName;
  }

  public void setItemName(String itemName) {
    this.itemName = itemName;
  }

  public int getQuantity() {
    return quantity;
  }

  public void setQuantity(int quantity) {
    this.quantity = quantity;
  }

  public int getCategoryID() {
    return categoryID;
  }

  public void setCategoryID(int categoryID) {
    this.categoryID = categoryID;
  }

  public String getExpirationDate() {
    return expirationDate;
  }

  public void setExpirationDate(String expirationDate) {
    this.expirationDate = expirationDate;
  }

  public String getNotes() {
    return notes;
  }

  public void setNotes(String notes) {
    this.notes = notes;
  }

  public boolean isExpirationRemindersEnabled() {
    return expirationRemindersEnabled;
  }

  public void setExpirationRemindersEnabled(boolean expirationRemindersEnabled) {
    this.expirationRemindersEnabled = expirationRemindersEnabled;
  }

  public int getNotifyDaysBefore() {
    return notifyDaysBefore;
  }

  public void setNotifyDaysBefore(int notifyDaysBefore) {
    this.notifyDaysBefore = notifyDaysBefore;
  }

  public boolean isNotifyOnZero() {
    return notifyOnZero;
  }

  public void setNotifyOnZero(boolean notifyOnZero) {
    this.notifyOnZero = notifyOnZero;
  }
}
