package com.example.emergencypreparednessmanager.entities;

import androidx.room.Entity;
import androidx.room.Ignore;
import androidx.room.PrimaryKey;

/**
 * Entity representing an emergency preparedness kit.
 * A kit may have multiple associated kit items.
 */
@Entity(tableName = "Kits")
public class Kit {

    // ------------------- DATABASE FIELDS -------------------

    @PrimaryKey(autoGenerate = true)
    private int kitID;

    private String kitName;
    private String location;
    private String notes;

    // ------------------- NOTIFICATION FIELDS -------------------
    // Optional reminder to review kit on a schedule, or a general kit reminder
    private boolean notificationsEnabled;
    private int notifyHour;
    private int notifyMinute;

    // ------------------- CONSTRUCTORS -------------------

    /**
     * Creates a new kit.
     * The kitID is auto-generated by Room.
     *
     * @param kitName              name of the kit
     * @param location             location of the kit
     * @param notes                notes
     * @param notificationsEnabled Whether notifications are enabled
     * @param notifyHour           Hour of the notification
     * @param notifyMinute         Minute of the notification
     */
    public Kit(
            String kitName,
            String location,
            String notes,
            boolean notificationsEnabled,
            int notifyHour,
            int notifyMinute
    ) {
        this.kitName = kitName;
        this.location = location;
        this.notes = notes;
        this.notificationsEnabled = notificationsEnabled;
        this.notifyHour = notifyHour;
        this.notifyMinute = notifyMinute;
    }

    /**
     * Creates an existing kit with a known ID.
     * Used for updates and deletions.
     *
     * @param kitID                Existing kit ID
     * @param kitName              name of the kit
     * @param location             location of the kit
     * @param notes                notes
     * @param notificationsEnabled Whether notifications are enabled
     * @param notifyHour           Hour of the notification
     * @param notifyMinute         Minute of the notification
     */
    @Ignore
    public Kit(
            int kitID,
            String kitName,
            String location,
            String notes,
            boolean notificationsEnabled,
            int notifyHour,
            int notifyMinute
    ) {
        this.kitID = kitID;
        this.kitName = kitName;
        this.location = location;
        this.notes = notes;
        this.notificationsEnabled = notificationsEnabled;
        this.notifyHour = notifyHour;
        this.notifyMinute = notifyMinute;
    }

    // ------------------- GETTERS AND SETTERS -------------------

    public int getKitID() {
        return kitID;
    }

    public void setKitID(int kitID) {
        this.kitID = kitID;
    }

    public String getKitName() {
        return kitName;
    }

    public void setKitName(String kitName) {
        this.kitName = kitName;
    }

    public String getLocation() {
        return location;
    }

    public void setLocation(String location) {
        this.location = location;
    }

    public String getNotes() {
        return notes;
    }

    public void setNotes(String notes) {
        this.notes = notes;
    }

    public boolean isNotificationsEnabled() {
        return notificationsEnabled;
    }

    public void setNotificationsEnabled(boolean notificationsEnabled) {
        this.notificationsEnabled = notificationsEnabled;
    }

    public int getNotifyHour() {
        return notifyHour;
    }

    public void setNotifyHour(int notifyHour) {
        this.notifyHour = notifyHour;
    }

    public int getNotifyMinute() {
        return notifyMinute;
    }

    public void setNotifyMinute(int notifyMinute) {
        this.notifyMinute = notifyMinute;
    }
}