package com.example.emergencypreparednessmanager.entities;

import androidx.room.Entity;
import androidx.room.Ignore;
import androidx.room.PrimaryKey;

/**
 * Entity representing an emergency preparedness kit.
 * A kit may have multiple associated kit items.
 * <p>
 * Notification model:
 * - notificationsEnabled: whether the kit gets reminders
 * - notificationFrequency: "MONTHLY", "QUARTERLY", "YEARLY"
 * - notification time is global (stored in Settings / SharedPreferences)
 */
@Entity(tableName = "Kits")
public class Kit {

    // ------------------- DATABASE FIELDS -------------------

    @PrimaryKey(autoGenerate = true)
    private int kitID;

    private String kitName;
    private String location;
    private String notes;

    // ------------------- NOTIFICATION FIELDS -------------------
    private boolean notificationsEnabled;
    private String notificationFrequency; // "MONTHLY", "QUARTERLY", "YEARLY"

    // ------------------- CONSTRUCTORS -------------------

    /**
     * Creates a new kit.
     * The kitID is auto-generated by Room.
     *
     * @param kitName               name of the kit
     * @param location              location of the kit
     * @param notes                 notes
     * @param notificationsEnabled  Whether notifications are enabled
     * @param notificationFrequency Frequency of notifications
     */
    public Kit(
            String kitName,
            String location,
            String notes,
            boolean notificationsEnabled,
            String notificationFrequency
    ) {
        this.kitName = kitName;
        this.location = location;
        this.notes = notes;
        this.notificationsEnabled = notificationsEnabled;
        this.notificationFrequency = notificationFrequency;
    }

    /**
     * Creates an existing kit with a known ID.
     * Used for updates and deletions.
     *
     * @param kitID                 Existing kit ID
     * @param kitName               name of the kit
     * @param location              location of the kit
     * @param notes                 notes
     * @param notificationsEnabled  Whether notifications are enabled
     * @param notificationFrequency Frequency of notifications
     */
    @Ignore
    public Kit(
            int kitID,
            String kitName,
            String location,
            String notes,
            boolean notificationsEnabled,
            String notificationFrequency
    ) {
        this.kitID = kitID;
        this.kitName = kitName;
        this.location = location;
        this.notes = notes;
        this.notificationsEnabled = notificationsEnabled;
        this.notificationFrequency = notificationFrequency;
    }

    // ------------------- GETTERS AND SETTERS -------------------

    public int getKitID() {
        return kitID;
    }

    public void setKitID(int kitID) {
        this.kitID = kitID;
    }

    public String getKitName() {
        return kitName;
    }

    public void setKitName(String kitName) {
        this.kitName = kitName;
    }

    public String getLocation() {
        return location;
    }

    public void setLocation(String location) {
        this.location = location;
    }

    public String getNotes() {
        return notes;
    }

    public void setNotes(String notes) {
        this.notes = notes;
    }

    public boolean isNotificationsEnabled() {
        return notificationsEnabled;
    }

    public void setNotificationsEnabled(boolean notificationsEnabled) {
        this.notificationsEnabled = notificationsEnabled;
    }

    public String getNotificationFrequency() {
        return notificationFrequency;
    }

    public void setNotificationFrequency(String notificationFrequency) {
        this.notificationFrequency = notificationFrequency;
    }
}
