package com.example.emergencypreparednessmanager.entities;

import androidx.room.Entity;
import androidx.room.Ignore;
import androidx.room.PrimaryKey;

/**
 * Entity representing an item stored within a kit.
 * Each item belongs to a single kit.
 * <p>
 * Notification model:
 * - Expiration reminders: enabled + notifyDaysBefore
 * - Quantity reminders: notify when quantity hits 0
 * - Notification time is global (stored in Settings / SharedPreferences)
 */
@Entity(tableName = "KitItems")

public class KitItem {

    // ------------------- DATABASE FIELDS -------------------

    @PrimaryKey(autoGenerate = true)
    private int itemID;

    private int kitID;
    private String itemName;
    private int quantity;
    private int categoryID;
    private String expirationDate; // "MM/dd/yyyy" (optional)
    private String notes;

    // ------------------- NOTIFICATION FIELDS -------------------

    private boolean expirationRemindersEnabled;
    private int notifyDaysBefore; // 0 = day-of, 3 = 3 days before, etc.
    private boolean notifyOnZero; // true = notify when quantity becomes 0

    // ------------------- CONSTRUCTORS -------------------

    /**
     * Creates a new kit item.
     * The itemID is auto-generated by Room.
     *
     * @param kitID                         Parent kit ID
     * @param itemName                      Item name
     * @param quantity                      Quantity stored
     * @param categoryID                    Category ID
     * @param expirationDate                Expiration date
     * @param notes                         Optional notes
     * @param expirationRemindersEnabled    Whether expiration reminders are enabled
     * @param notifyDaysBefore              Number of days before expiration to notify
     * @param notifyOnZero                  Whether to notify when quantity reaches zero
     */
    public KitItem(
            int kitID,
            String itemName,
            int quantity,
            int categoryID,
            String expirationDate,
            String notes,
            boolean expirationRemindersEnabled,
            int notifyDaysBefore,
            boolean notifyOnZero
    ) {
        this.kitID = kitID;
        this.itemName = itemName;
        this.quantity = quantity;
        this.categoryID = categoryID;
        this.expirationDate = expirationDate;
        this.notes = notes;
        this.expirationRemindersEnabled = expirationRemindersEnabled;
        this.notifyDaysBefore = notifyDaysBefore;
        this.notifyOnZero = notifyOnZero;

    }

    /**
     * Creates an existing kit item with a known ID.
     * Used for updates and deletions.
     *
     * @param itemID                        Existing item ID
     * @param kitID                         Parent kit ID
     * @param itemName                      Item name
     * @param quantity                      Quantity stored
     * @param categoryID                    Category ID
     * @param expirationDate                Expiration date
     * @param notes                         Optional notes
     * @param expirationRemindersEnabled    Whether expiration reminders are enabled
     * @param notifyDaysBefore              Number of days before expiration to notify
     * @param notifyOnZero                  Whether to notify when quantity reaches zero
     */
    @Ignore
    public KitItem(
            int itemID,
            int kitID,
            String itemName,
            int quantity,
            int categoryID,
            String expirationDate,
            String notes,
            boolean expirationRemindersEnabled,
            int notifyDaysBefore,
            boolean notifyOnZero
    ) {
        this.itemID = itemID;
        this.kitID = kitID;
        this.itemName = itemName;
        this.quantity = quantity;
        this.categoryID = categoryID;
        this.expirationDate = expirationDate;
        this.notes = notes;
        this.expirationRemindersEnabled = expirationRemindersEnabled;
        this.notifyDaysBefore = notifyDaysBefore;
        this.notifyOnZero = notifyOnZero;
    }

    // ------------------- GETTERS AND SETTERS -------------------

    public int getItemID() {
        return itemID;
    }

    public void setItemID(int itemID) {
        this.itemID = itemID;
    }

    public int getKitID() {
        return kitID;
    }

    public void setKitID(int kitID) {
        this.kitID = kitID;
    }

    public String getItemName() {
        return itemName;
    }

    public void setItemName(String itemName) {
        this.itemName = itemName;
    }

    public int getQuantity() {
        return quantity;
    }

    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }

    public int getCategoryID() {
        return categoryID;
    }

    public void setCategoryID(int categoryID) {
        this.categoryID = categoryID;
    }

    public String getExpirationDate() {
        return expirationDate;
    }

    public void setExpirationDate(String expirationDate) {
        this.expirationDate = expirationDate;
    }

    public String getNotes() {
        return notes;
    }

    public void setNotes(String notes) {
        this.notes = notes;
    }

    public boolean isExpirationRemindersEnabled() {
        return expirationRemindersEnabled;
    }

    public void setExpirationRemindersEnabled(boolean expirationRemindersEnabled) {
        this.expirationRemindersEnabled = expirationRemindersEnabled;
    }

    public int getNotifyDaysBefore() {
        return notifyDaysBefore;
    }

    public void setNotifyDaysBefore(int notifyDaysBefore) {
        this.notifyDaysBefore = notifyDaysBefore;
    }

    public boolean isNotifyOnZero() {
        return notifyOnZero;
    }

    public void setNotifyOnZero(boolean notifyOnZero) {
        this.notifyOnZero = notifyOnZero;
    }
}
