package com.example.emergencypreparednessmanager.entities;

import androidx.room.Entity;
import androidx.room.Ignore;
import androidx.room.PrimaryKey;

/**
 * Entity representing an item stored within a kit.
 * Each item belongs to a single kit.
 */
@Entity(tableName = "KitItems")

public class KitItem {

    // ------------------- DATABASE FIELDS -------------------

    @PrimaryKey(autoGenerate = true)
    private int itemID;

    private int kitID;
    private String itemName;
    private int quantity;
    private int categoryID;
    private String expirationDate;
    private String notes;

    // ------------------- NOTIFICATION FIELDS -------------------

    private boolean notificationsEnabled;
    private int notifyHour;
    private int notifyMinute;

    // ------------------- CONSTRUCTORS -------------------

    /**
     * Creates a new kit item.
     * The itemID is auto-generated by Room.
     *
     * @param kitID                 Parent kit ID
     * @param itemName              Item name
     * @param quantity              Quantity stored
     * @param categoryID            Category ID
     * @param expirationDate        Expiration date
     * @param notes                 Optional notes
     * @param notificationsEnabled  Whether notifications are enabled
     * @param notifyHour            Hour of the notification
     * @param notifyMinute          Minute of the notification
     */
    public KitItem(
            int kitID,
            String itemName,
            int quantity,
            int categoryID,
            String expirationDate,
            String notes,
            boolean notificationsEnabled,
            int notifyHour,
            int notifyMinute
    ) {
        this.kitID = kitID;
        this.itemName = itemName;
        this.quantity = quantity;
        this.categoryID = categoryID;
        this.expirationDate = expirationDate;
        this.notes = notes;
        this.notificationsEnabled = notificationsEnabled;
        this.notifyHour = notifyHour;
        this.notifyMinute = notifyMinute;
    }

    /**
     * Creates an existing kit item with a known ID.
     * Used for updates and deletions.
     *
     * @param itemID                Existing item ID
     * @param kitID                 Parent kit ID
     * @param itemName              Item name
     * @param quantity              Quantity stored
     * @param categoryID            Category ID
     * @param expirationDate        Expiration date
 * @param notes                     Optional notes
     * @param notificationsEnabled  Whether notifications are enabled
     * @param notifyHour            Hour of the notification
     * @param notifyMinute          Minute of the notification
     */
    @Ignore
    public KitItem(
            int itemID,
            int kitID,
            String itemName,
            int quantity,
            int categoryID,
            String expirationDate,
            String notes,
            boolean notificationsEnabled,
            int notifyHour,
            int notifyMinute
    ) {
        this.itemID = itemID;
        this.kitID = kitID;
        this.itemName = itemName;
        this.quantity = quantity;
        this.categoryID = categoryID;
        this.expirationDate = expirationDate;
        this.notes = notes;
        this.notificationsEnabled = notificationsEnabled;
        this.notifyHour = notifyHour;
        this.notifyMinute = notifyMinute;
    }

    // ------------------- GETTERS AND SETTERS -------------------

    public int getItemID() {
        return itemID;
    }

    public void setItemID(int itemID) {
        this.itemID = itemID;
    }

    public int getKitID() {
        return kitID;
    }

    public void setKitID(int kitID) {
        this.kitID = kitID;
    }

    public String getItemName() {
        return itemName;
    }

    public void setItemName(String itemName) {
        this.itemName = itemName;
    }

    public int getQuantity() {
        return quantity;
    }

    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }

    public int getCategoryID() {
        return categoryID;
    }

    public void setCategoryID(int categoryID) {
        this.categoryID = categoryID;
    }

    public String getExpirationDate() {
        return expirationDate;
    }

    public void setExpirationDate(String expirationDate) {
        this.expirationDate = expirationDate;
    }

    public String getNotes() {
        return notes;
    }

    public void setNotes(String notes) {
        this.notes = notes;
    }

    public boolean isNotificationsEnabled() {
        return notificationsEnabled;
    }

    public void setNotificationsEnabled(boolean notificationsEnabled) {
        this.notificationsEnabled = notificationsEnabled;
    }

    public int getNotifyHour() {
        return notifyHour;
    }

    public void setNotifyHour(int notifyHour) {
        this.notifyHour = notifyHour;
    }

    public int getNotifyMinute() {
        return notifyMinute;
    }

    public void setNotifyMinute(int notifyMinute) {
        this.notifyMinute = notifyMinute;
    }
}
